# Generated by Django 3.1.2 on 2020-10-02 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pescod', '0001_initial'),
        ('users_groups', '0001_initial'),
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_trusty', models.BooleanField(default=False, help_text='Designates whether this user has confirmed his account.', verbose_name='trusty')),
                ('ativo', models.PositiveIntegerField(blank=True, null=True)),
                ('login', models.CharField(max_length=25)),
                ('nome', models.CharField(blank=True, max_length=25, null=True)),
                ('numlog', models.PositiveIntegerField(blank=True, null=True)),
                ('senha', models.CharField(max_length=20)),
                ('acess', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=255, verbose_name='Acesso')),
                ('desenv', models.PositiveIntegerField(blank=True, null=True, verbose_name='Desenvolvedor')),
                ('datsenha', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_de_exclusao', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('idgrp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users_groups.usersgrp', verbose_name='ID grupo')),
                ('idpescod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pescod.pescod', verbose_name='ID registro pessoa')),
                ('instit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicao.instit', verbose_name='ID instituição')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
