# Generated by Django 3.1.2 on 2020-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201002_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='last name'),
        ),
    ]
