# Generated by Django 3.1.2 on 2020-11-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pescod', '0002_auto_20201105_1848'),
        ('instituicao', '0001_initial'),
        ('users_groups', '0001_initial'),
        ('users', '0003_auto_20201002_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='idgrp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users_groups.usersgrp', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='users',
            name='idpescod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pescod.pescod', verbose_name='registro pessoa'),
        ),
        migrations.AlterField(
            model_name='users',
            name='instit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicao.instit', verbose_name='instituição'),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='senha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
