# Generated by Django 3.1.2 on 2020-11-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201105_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
