# Generated by Django 3.1.2 on 2020-10-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pescod',
            fields=[
                ('id_pessoa_cod', models.AutoField(primary_key=True, serialize=False)),
                ('id_instituicao_fk', models.IntegerField()),
                ('tipo', models.PositiveIntegerField()),
                ('sit', models.PositiveIntegerField()),
                ('forn', models.PositiveIntegerField()),
                ('cpfcnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('nomeorrazaosocial', models.CharField(blank=True, db_column='nomeOrRazaoSocial', max_length=100, null=True, unique=True)),
                ('foto', models.CharField(max_length=25)),
                ('img_bites', models.PositiveIntegerField()),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pescod',
                'managed': False,
            },
        ),
    ]
