# Generated by Django 3.1.2 on 2020-11-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pescod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pescod',
            options={'managed': False, 'ordering': ['nomeorrazaosocial']},
        ),
    ]
