# Generated by Django 3.1.2 on 2020-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotinas',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=40)),
                ('sit', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'rotinas',
                'ordering': ['descr'],
                'managed': False,
            },
        ),
    ]
