# Generated by Django 3.1.2 on 2020-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesjur',
            fields=[
                ('id_pessoa_juridica', models.AutoField(primary_key=True, serialize=False)),
                ('id_pessoa_cod_fk', models.IntegerField()),
                ('fantasia', models.CharField(blank=True, max_length=50, null=True)),
                ('ramo', models.CharField(blank=True, max_length=255, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('capsocial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('faturamento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tribut', models.PositiveIntegerField()),
                ('contato', models.CharField(blank=True, max_length=25, null=True)),
                ('data_abertura', models.DateField()),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pesjur',
                'managed': False,
            },
        ),
    ]
