# Generated by Django 3.1.2 on 2020-10-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instit',
            fields=[
                ('id_instituicao', models.IntegerField(primary_key=True, serialize=False)),
                ('idmatriz', models.PositiveIntegerField()),
                ('idpjur', models.PositiveIntegerField()),
                ('ativo', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=40)),
                ('razsoc', models.CharField(blank=True, max_length=80, null=True)),
                ('endtip', models.PositiveIntegerField()),
                ('end', models.CharField(blank=True, max_length=50, null=True)),
                ('endnum', models.CharField(blank=True, max_length=8, null=True)),
                ('endcompl', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, max_length=40, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.PositiveIntegerField()),
                ('uf', models.PositiveIntegerField()),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('iest', models.CharField(blank=True, max_length=25, null=True)),
                ('imun', models.CharField(blank=True, max_length=10, null=True)),
                ('mail1', models.CharField(max_length=60)),
                ('mail2', models.CharField(blank=True, max_length=60, null=True)),
                ('tel1', models.CharField(blank=True, max_length=14, null=True)),
                ('tel2', models.CharField(blank=True, max_length=14, null=True)),
                ('tel3', models.CharField(blank=True, max_length=14, null=True)),
                ('fax', models.CharField(blank=True, max_length=13, null=True)),
                ('slogan', models.CharField(blank=True, max_length=60, null=True)),
                ('modulos', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instit',
                'managed': False,
            },
        ),
    ]
