# Generated by Django 3.1.2 on 2020-10-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGrp',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=15)),
                ('instit', models.IntegerField()),
                ('acess', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_grp',
                'managed': False,
            },
        ),
    ]
