# Generated by Django 3.1.2 on 2020-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesfis',
            fields=[
                ('id_pessoa_fisica', models.AutoField(primary_key=True, serialize=False)),
                ('id_pessoa_cod_fk', models.IntegerField()),
                ('identidade', models.CharField(max_length=20)),
                ('emissor_identidade', models.CharField(max_length=50)),
                ('id_municipio_fk', models.IntegerField()),
                ('id_uf_municipio_fk', models.IntegerField()),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('tratam', models.PositiveIntegerField()),
                ('apelido', models.CharField(blank=True, max_length=25, null=True)),
                ('sexo', models.CharField(max_length=20)),
                ('pai', models.CharField(blank=True, max_length=60, null=True)),
                ('mae', models.CharField(blank=True, max_length=60, null=True)),
                ('profissao', models.CharField(blank=True, max_length=30, null=True)),
                ('ctps', models.CharField(blank=True, max_length=15, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('resp', models.CharField(blank=True, max_length=25, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('iest', models.CharField(blank=True, max_length=20, null=True)),
                ('imun', models.CharField(blank=True, max_length=15, null=True)),
                ('emprend', models.CharField(max_length=200)),
                ('orendas', models.CharField(blank=True, max_length=50, null=True)),
                ('vrendas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irpf', models.PositiveIntegerField()),
                ('estcivil', models.PositiveIntegerField()),
                ('depend', models.PositiveIntegerField()),
                ('pensao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conjuge', models.CharField(blank=True, max_length=60, null=True)),
                ('cpfconj', models.CharField(blank=True, max_length=14, null=True)),
                ('profconj', models.CharField(blank=True, max_length=30, null=True)),
                ('emprconj', models.CharField(blank=True, max_length=50, null=True)),
                ('rendaconj', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telconj', models.CharField(blank=True, max_length=11, null=True)),
                ('mailconj', models.CharField(blank=True, max_length=50, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pesfis',
                'managed': False,
            },
        ),
    ]
