# Generated by Django 3.1.2 on 2020-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id_enderecos', models.AutoField(primary_key=True, serialize=False)),
                ('situacao', models.IntegerField()),
                ('origem', models.PositiveIntegerField()),
                ('id_pessoa_cod_fk', models.IntegerField()),
                ('endtip', models.PositiveIntegerField()),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=40, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_endereco', models.CharField(blank=True, max_length=3, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enderecos',
                'managed': False,
            },
        ),
    ]
