# Generated by Django 3.1.2 on 2020-10-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagensusuarios',
            old_name='instit_id',
            new_name='instit',
        ),
        migrations.RenameField(
            model_name='imagensusuarios',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='imagensusuarios',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
